profile page
okokanya/twitter-demo-frontend pull request #1
Opened 2018-06-20 07:27 UTC by okokanya

2018-06-20 22:49 UTC, evgenyrodionov commented
смени название репозитрия на нормальное

2018-06-20 22:53 UTC, imevro requested changes
преттир не настроен, документация инструментов не читана, частые ошибки тоже мимо прошли

2018-06-20 22:53 UTC, evgenyrodionov commented on .eslintrc
> +    "arrow-parens": [
зачем ты сделала свои правила еслинта?

2018-06-20 22:53 UTC, evgenyrodionov commented on .eslintrc
> +    "arrow-parens": [
удаляй это всё

2018-06-20 22:53 UTC, evgenyrodionov commented on src/App.js
> +import Profile from './pages/Profile';
зачем тебе лишняя сущность pages? ради чего? упрощай

2018-06-20 22:53 UTC, evgenyrodionov commented on src/App.js
> +import Header from './header/Header';
→ `/Header/index.js`

2018-06-20 22:53 UTC, evgenyrodionov commented on src/ProfileDescription.js
> +    svg {
читай частые ошибки, нельзя так делать

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Feed.js
> +class Feed extends Component {
зачем ты используешь классы?

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Feed.js
> +          stat={[0, 2, 3, 4]}
зачем массив? как понять что есть что?

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Feed.js
> +          time="23h"
date-fns.org + передавай всегда сырое значение и форматируй по факту там где нужно

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Feed.js
> +          doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
не очень похоже на текст с макета

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Tweet.js
> +const TweetAvatar = styled.div `
ты и так в файле твит, зачем столько префиксов твит

2018-06-20 22:53 UTC, evgenyrodionov commented on src/feed/Tweet.js
> +import React from 'react';
feed → Feed

2018-06-20 22:53 UTC, evgenyrodionov commented on src/header/Header.js
> +} from '../ui/Icon.js';
.жс можно опустить, вебпак и так сам ищет джс файлы при импорте

2018-06-20 22:53 UTC, evgenyrodionov commented on src/header/Header.js
> +  height: 50px;
высоту или ширину только картинкам

2018-06-20 22:53 UTC, evgenyrodionov commented on src/pages/Profile.js
> +  > div {
мало того что по тегам стилизовать нельзя, так ещё и самый ненадежный селектор

2018-06-20 22:53 UTC, evgenyrodionov commented on src/pages/Profile.js
> +            <Stat number="1,815" title="Followers" />
почему ты число передаёшь как строку?

2018-06-20 22:53 UTC, evgenyrodionov commented on src/pages/Profile.js
> +            <Stat number="8,058" title="Tweets" active />
с этим active ты зачем-то делаешь работу за компонент NavLink в реакт-роутере

2018-06-20 22:53 UTC, evgenyrodionov commented on src/ui/Avatar.js
> +background-color: white;
ну и чё тут со стилем кода?

2018-06-21 07:58 UTC, okokanya commented on src/pages/Profile.js
> +            <Stat number="8,058" title="Tweets" active />
это временно ) пока нет нужных маршрутов, можно так оставить?

2018-06-21 12:13 UTC, okokanya commented
Привет! Исправила!

2018-06-25 16:01 UTC, imevro requested changes
пройдись преттиром и настрой его в редакторе, чисто треш какой-то

2018-06-25 16:01 UTC, evgenyrodionov commented on src/LinksBlock.js
> +  a {
нет, по тегам стилизовать можно только когда нет доступа до элемента

2018-06-25 16:01 UTC, evgenyrodionov commented on src/ProfileDescription.js
> +import Avatar3 from './img/Avatar3.png';
в паблик директорию

2018-06-25 16:01 UTC, evgenyrodionov commented on src/Ui/Colors.js
> +export const color = {
множ число

2018-06-25 16:01 UTC, evgenyrodionov commented on src/Ui/Margin.js
> +margin-right: 5px;
во-первых почему преттир не настроен

во-вторых что за странное название компонента

2018-06-25 16:01 UTC, evgenyrodionov commented on src/ui/Avatar.js
> +    ? '80px'
не нужно плодить вложенные тернарники

2018-06-25 16:01 UTC, evgenyrodionov commented
Как исправишь — сделай мердж через сквош (это мердж, который все коммиты в бранче схлопывает в один)

Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап

2018-06-25 21:03 UTC, merged