Feat/routing
okokanya/twitter-demo-frontend pull request #2
Opened 2018-06-27 07:56 UTC by okokanya

руты настроены только для юзера, airbnb-конфиг еще не подключила

2018-06-27 21:23 UTC, imevro requested changes

2018-06-27 21:23 UTC, evgenyrodionov commented on src/App.js
> +            <Route exact path="/:user/likes" component={Profile} />
ты теряешь смысл реакт-роутера

Философия его строится вокруг «когда путь совпал — отрендерь в этом месте компонент X»

Понимаешь? Вот твои ссылки щас проебут все боковые меню которые есть на странице профиля

2018-06-27 21:23 UTC, evgenyrodionov commented on src/Ui/Margin.js
> +const Margin = styled.div`
я же вроде говорил что это супердерьмовый компонент?

2018-06-27 21:23 UTC, evgenyrodionov commented on src/data.js
> +import Avatar5 from './img/Avatar5.png';
PascalCase только для компонентов это раз

контентный мусор в паблик директории это два

2018-06-27 21:23 UTC, evgenyrodionov commented on src/data.js
> +import re3 from './img/re3.png';
что с неймингом? вообще его не понимаю

2018-06-29 04:07 UTC, okokanya commented on src/Ui/Margin.js
> +const Margin = styled.div`
убрала

2018-06-29 05:09 UTC, okokanya commented on src/data.js
> +import Avatar5 from './img/Avatar5.png';
PascalCase поменяла, картинки записала в константу и раздаю оттуда

2018-06-29 05:17 UTC, okokanya commented on src/data.js
> +import re3 from './img/re3.png';
переименовала

2018-06-29 22:07 UTC, imevro requested changes

2018-06-29 22:07 UTC, evgenyrodionov commented on src/App.js
> +import SomePage from './somePage';
почему camelCase у файла

2018-06-29 22:07 UTC, evgenyrodionov commented on src/App.js
> +        <Route path="/i" component={SomePage} />
i?

2018-06-29 22:07 UTC, evgenyrodionov commented on src/App.js
> +        <Route exact path="/:user/likes" component={Profile} />
этому всему место в профиле, а не в аппджсе

2018-06-29 22:07 UTC, evgenyrodionov commented on src/header/Header.js
> +  div {
блядь, в очередной раз повторяю что по тегам не стилизуем

2018-06-29 22:07 UTC, evgenyrodionov commented on src/header/Header.js
> +  div {
это троллинг какой-то?

2018-06-29 22:07 UTC, evgenyrodionov commented on src/header/Header.js
> +          <NavItemImg>
если у тебя столько префиксов нав нав нав, то явный признак что нужно выносить в отдельный компонент

2018-06-29 22:07 UTC, evgenyrodionov commented on src/img/allImages.js
> +import avatar6 from './avatar6.png';
все контентные изображения в паблик директорию

2018-07-03 10:12 UTC, okokanya commented on src/App.js
> +import SomePage from './somePage';
убрала

2018-07-03 10:13 UTC, okokanya commented on src/img/allImages.js
> +import avatar6 from './avatar6.png';
перенесла

2018-07-03 11:07 UTC, okokanya commented on src/header/Header.js
> +  div {
убрала

2018-07-03 12:18 UTC, okokanya commented on src/header/Header.js
> +          <NavItemImg>
переименовала, зачем там префиксы ..

2018-07-05 16:38 UTC, okokanya commented on src/App.js
> +        <Route path="/i" component={SomePage} />
i - это маршрут со страницей-плейсхолдером (для ссылок из верхнего меню)

2018-07-05 16:41 UTC, okokanya commented on src/App.js
> +        <Route exact path="/:user/likes" component={Profile} />
убрала

2018-07-06 08:27 UTC, okokanya commented
исправила правки, сделала задание по api

2018-07-06 20:22 UTC, imevro requested changes

2018-07-06 20:22 UTC, evgenyrodionov commented on .eslintrc
> +    "class-methods-use-this": 0
кто разрешал трогать правила?

2018-07-06 20:22 UTC, evgenyrodionov commented on .gitignore
> +/src/config.js
?

2018-07-06 20:22 UTC, evgenyrodionov commented on .prettierrc
> +  "trailingComma": "all"
вообще снеси этот файл, преттир не должен настраиваться

2018-07-06 20:22 UTC, evgenyrodionov commented on package.json
> +    "axios": "^0.18.0",
фетч

2018-07-06 20:22 UTC, evgenyrodionov commented on src/Ui/LeftSideBlock.js
> +import colors from './Colors';
колорс это компонент? поч с большой буквы?

2018-07-06 20:22 UTC, evgenyrodionov commented on src/feed/Feed.js
> +import API_KEY from '../config';
энв параметры есть для этого

2018-07-06 20:22 UTC, evgenyrodionov commented on src/feed/Feed.js
> +    console.log(this.state.statusList);
мусор

2018-07-06 20:22 UTC, evgenyrodionov commented on src/feed/Feed.js
> +          <StyledLink activeClassName="active" to={`/${user}/tweet`}>
по дефолту и так active

2018-07-06 20:22 UTC, evgenyrodionov commented on src/feed/Feed.js
> +        <FeedTabs>
ты и так в файле feed

2018-07-06 20:22 UTC, evgenyrodionov commented on src/feed/Tweet.js
> +  img {
нет?

2018-07-06 20:22 UTC, evgenyrodionov commented on src/header/Header.js
> +          </ItemImg>
хуитем

2018-07-07 09:11 UTC, okokanya commented on .gitignore
> +/src/config.js
перенесла api key в .env

2018-07-07 09:34 UTC, okokanya commented on .eslintrc
> +    "class-methods-use-this": 0
"arrow-parens" и "no-confusing-arrow" конфликтует с притиром,
jsx-a11y/anchor-is-valid заставляет использовать href в <Link>, 
class-methods-use-this заставляет использовать this в геттерах. Не поняла зачем, убрала,
react/jsx-filename-extension и react/prop-types -- ты говорил убрать

2018-07-07 10:06 UTC, okokanya commented on src/Ui/LeftSideBlock.js
> +import colors from './Colors';
поправила

2018-07-07 10:09 UTC, okokanya commented on src/feed/Tweet.js
> +  img {
это компонент только для аватарки! тут сто проц больше ничего не будет

2018-07-07 12:23 UTC, okokanya commented on package.json
> +    "axios": "^0.18.0",
поменяла

2018-07-07 12:32 UTC, okokanya commented on src/feed/Feed.js
> +import API_KEY from '../config';
убрала да

2018-07-07 12:36 UTC, okokanya commented on src/feed/Feed.js
> +    console.log(this.state.statusList);
убрала

2018-07-07 12:40 UTC, okokanya commented on src/feed/Feed.js
> +          <StyledLink activeClassName="active" to={`/${user}/tweet`}>
убрала

2018-07-07 12:41 UTC, okokanya commented on src/feed/Feed.js
> +        <FeedTabs>
переименовала

2018-07-07 12:46 UTC, okokanya commented on src/header/Header.js
> +          </ItemImg>
переименовала

2018-07-07 13:28 UTC, okokanya commented on .prettierrc
> +  "trailingComma": "all"
они с эслинтом конфликтуют без этого

2018-07-13 20:23 UTC, evgenyrodionov commented on src/feed/Tweet.js
> +  img {
аватарку ты не можешь контролировать или что? не понял

2018-07-13 20:23 UTC, evgenyrodionov commented on src/feed/Tweet.js
> +  img {
делай нормальный компонент

2018-07-13 20:23 UTC, evgenyrodionov commented on .prettierrc
> +  "trailingComma": "all"
они с еслинтом конфликтуют потому что ты свой редактор не настроила

2018-07-13 20:23 UTC, evgenyrodionov commented on .eslintrc
> +    "class-methods-use-this": 0
1) настрой редактор
2) настрой правило, а не выключай
3) перечитай внимательнее о правиле

2018-07-13 20:24 UTC, closed without merging

2018-07-13 20:24 UTC, imevro commented on src/config.js
> +  'c39eeff95215546db72a5e02362d40b474a2c724c4fd1b04789ac0cf7f358bd3';
блядь, ну я же сказал